version: '3'
services:
  api:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/users.db:/app/users.db

  ui:
    build: ./enter_ui
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8001
